### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: base.html

### ISSUE THREAD

**Issue by abubelinha** [wcchin/pyreveal#1]
I am trying to use your program (Windows 7, Python 3.8) but I am not sure I installed it correctly.
I guess there is no way to use `pip install pyreveal`, and I don't use git.
So I installed it [this way](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch/24811490#comment63766323_24811490) instead, which worked for me with some other github python projects:
```
C:\Python38\scripts\pip install --upgrade  https://github.com/wcchin/pyreveal/archive/master.tar.gz
(...)
Successfully installed pyreveal-0.1.2
```
Then I tried to run it like this:
```
C:\Python38\scripts\pyreveal -h
Usage: pyreveal [options]

Options:
  -h, --help            show this help message and exit
  -i SLIDES.md, --input=SLIDES.md
                        markdown file holding your slides and configs
  -w, --watch
```
So it looks to be installed.
Then I downloaded [demo.md](https://github.com/wcchin/pyreveal/blob/master/slide_dir/demo.md) and tried this command:
```
C:\Python38\scripts\pyreveal -i demo.md -w
processing: demo.md
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\scripts\pyreveal.exe\__main__.py", line 7, in <module>
  File "C:\Python38\lib\site-packages\pyreveal\pyreveal.py", line 39, in main
    S = slides(options.filename)
  File "C:\Python38\lib\site-packages\pyreveal\pyreveal.py", line 209, in __init__
    template = templateEnv.get_template( TEMPLATE_FILE )
  File "C:\Python38\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Python38\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Python38\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Python38\lib\site-packages\jinja2\loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: base.html
```
As far as I know, jinja2 is being used correctly by other Python packages I installed, like [pdoc](https://github.com/mitmproxy/pdoc/).

Any ideas of how to make this work?
Should I download your whole zipped repository and uncompress it somewhere, instead of trying to install it as a Python package?

Many thanks in advance
@abubelinha

**Comment by wcchin** [comment]
Hi, I did not test it with Windows and the normal install, so a mistake was made in the setup.py for general usage (my bad). 

The problem is not from the jinja2, it is the pyreveal did not install the `base.html` file to the package folder (because of my mistake).  

I corrected the setup.py now for the normal installation (e.g., your install method). You can try to uninstall it with (`pip uninstall pyreveal`) then reinstall it again and see if it fixes the error. 

Another way of installing is to download the entire repository using `Download ZIP` in the drop-down list of the `Code` button, unzip it, and install the package with the `-e` option, the template file will be downloaded and located in the unzipped folder where it is installed. With the `-e` option, it means it is editable under the unzipped folder. I believe it should be fine without the `-e` option as well.

**Comment by abubelinha** [comment]
Thanks a lot for fixing.
I repeated the same installation process as before.
I guess it worked since that `TemplateNotFound` error is gone.

Unfortunately now I get a different error, which is a bit more cryptic to me:
```
C:\Python38\scripts\pyreveal -i demo.md -w
processing: demo.md
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\scripts\pyreveal.exe\__main__.py", line 7, in <module>
  File "C:\Python38\lib\site-packages\pyreveal\pyreveal.py", line 39, in main
    S = slides(options.filename)
  File "C:\Python38\lib\site-packages\pyreveal\pyreveal.py", line 103, in __init__
    doc, config = self.process_md(afile)
  File "C:\Python38\lib\site-packages\pyreveal\pyreveal.py", line 243, in process_md
    doc = f.read()
  File "C:\Python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 256110: character maps to <undefined>
```

**Comment by abubelinha** [comment]
Sorry, my bad!  It was a wrong demo.md download. 
I'll try it later when I have more time.

**Comment by abubelinha** [comment]
Sorry, my bad!  It was a wrong [demo.md](https://github.com/wcchin/pyreveal/blob/master/slide_dir/demo.md) download. 

I tried again and now it produced an .html file with plain blue background, but nothing else.
I used Chrome DevTools to see the console and I see:
- A "custom.css file not found" error, which I solved by creating a blank custom.css file
- A bunch of `GET https://wcc-slides.netlify.app/reveal.js/css/...WHATEVER.css net::ERR_ABORTED 404` errors  
  (where _...WHATEVER.css_ are different .css files in different paths)

Looks like `reveal_path` in `base.html` is pointing to an old url which does not exist?

BTW, I tried this without the -w option. 
And then I opened the created .html in my browser by double clicking it ... so the Chrome navigator url is 
`file:///C:/my_output_folder/demo.slides.html`

Should the slides work this way, without a web server? 
(so I can send my presentation to anybody in a zip with `demo.slides.html` and `custom.css`)

Thanks a lot for your help!

**Comment by wcchin** [comment]
No worry. I believe it can be an error from the OS different. I am developing it on a Linux machine, and I don't have a Windows machine to test. I added an encoding to the line that cause the error (open file step). Please uninstall and install again to see if it eliminate the problem. 

Also, I changed a little bit to the demo.md file so that it will use a local copy of js resources (that should be installed with the latest edit). 

Thanks for testing.

**Comment by wcchin** [comment]
> 

Hi. Yes, I found that issue during the last edit. Please try the new demo.md, or remove the line `reveal_path` from the yaml config. 

With this line removed, it should copy the reveal_js folder from the installed package and use it in the presentation.  

Also, please reinstall it. Because the folder is missing from the previous installation process.

**Comment by abubelinha** [comment]
> With this line removed, it should copy the reveal_js folder from the installed package and use it in the presentation.

This worked great now, thanks!!    But I have a question.
That generated `reveal.js` folder is about 15-20 MB and I understand I cannot distribute my presentation without it.
That's OK for my tests, but for production I would prefer not to do that.
`reveal_path` should still permit to read required .js or .css files online from reveal.js or cdn repository, shouldn't it?

Is it possible to configure `pyreveal` that way ... so I can distribute just a small zip file containing `slides.html` (plus any images or .css files I could need to use)? 
I am assuming the audience browsers have internet connection (to load reveal.js stuff online), so I had two possible use cases:
- click `slides.html` from my unzipped files carried in a USB pen or sent by email (not needing to use a web server for them).
- or I can serve my unzipped files from my own webserver (but without serving the 15-20 MB reveal.js files myself)

I understand this line you removed at the end of demo.md file does the trick:
`reveal_path: https://wcc-slides.netlify.com/reveal.js
`
So that should be changed to a different server which does work. Correct?

Thanks a lot for your support!

**Comment by wcchin** [comment]
Glad that it works now. 

You are absolutely correct about the path. Removing the `reveal_path` will force the script to make a copy of the reveal.js files to the local folder and link to it. 

The keyword should still works and I believe it should works with the public CDN of reveal.js (I am not sure about this). 
You can try this, e.g., 

```
reveal_path: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.6.0/js/reveal.min.js
```
and see if it works. Some of the functions may not work directly, e.g., the TOC, equation etc. are the plugins for reveal.js, which require some other CDN paths. 

I prefer to host it on the same space I upload my slides, so that if anything wrong, everything is under control. So what I have done is host all my slides at the same site, sharing the same reveal js files. One reason is that I usually present this on my machine (e.g., in a conference) and the internet connection may be unstable. 

Also, a workaround is to manually change all the js / CSS file (except the custom.css or the customize theme CSS file that should be local) paths to a public CDN after the slide HTML file is done. 

Assuming that you have configure the reveal.js CDN path correctly (for all the relevant js and CSS files, except the custom.css if you have used it, if not, remove the line for the custom.css): 
- Yes, the single HTML file should run on USB or sent by email, 
- you can serve the single HTML file on your server without serving the 15-20mb files.

**Comment by abubelinha** [comment]
Thanks a lot for your explanations. 

> I prefer to host it on the same space I upload my slides, so that if anything wrong, everything is under control. (...)
> One reason is that I usually present this on my machine (e.g., in a conference) and the internet connection may be unstable.

:thinking:  Sounds reasonable. 

So you installed a particular reveals.js version ([3.8.0 in your repository](https://github.com/wcchin/pyreveal/blob/master/pyreveal/reveal_js/js/reveal.js#L29)) and then put together all [different plugins](https://github.com/wcchin/pyreveal/tree/master/pyreveal/reveal_js/plugin) you needed to use ... which might be stored in different CDN paths making it best your choice of a single server (I tried different `reveal_path` values, but there are always some missing files; I guess it's due to [path changes in different major versions](https://github.com/cdnjs/packages/pull/335)).

I'll probably do the same, except for one thing: my biggest concern is your `css/fontawesome` folder (10 MB and lots of files, which I'd prefer to avoid, or load from CDN).

Regarding markdown, I looked a bit to your demo.md file, particularly slide transitions:
I figure out your python code is expecting a particular way of indicating vertical (`---down`) or horizontal (`---right`) transitions in the `demo.md` file.  And then python converts them to html sections already, correct? 
And the same happens to most of the markdown content in `demo.md` ... except the script content in this part:

```
---data-markdown
<script type="text/template">
    ## Markdown support

    Write content using inline or external Markdown.
    Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).

    ```
    <section data-markdown>
      ## Markdown support

      Write content using inline or external Markdown.
      Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
    </section>
    ```
</script>
```

Such `---data-markdown` sections expect a different markdown format (which reveal.js should process using the markdown.js plugin). Correct?  So that markdown format could use different slide transition marks than those in your demo.md

Just asking to be sure I understand how it works (want to avoid confusion between python-processed-markdown and browser-processed-markdown).

Thanks a lot again!
